version: "3"
services:
  strapi:
    build: ./app
    image: strapi:v4
    container_name: strapiv4
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgresDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./app/config:/srv/app/config
      - ./app/src:/srv/app/src
      - ./app/.env:/srv/app/.env
    ports:
      - "1337:1337"
    networks:
      - strapi-network
    depends_on:
      - postgresDB

  postgresDB:
    image: postgres:14.2
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi-network

networks:
  strapi-network:
    name: strapi-network
    driver: bridge
